# Generated by Django 4.2.7 on 2023-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
