# Generated by Django 4.2.7 on 2023-11-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_person_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surrname'], 'permissions': [('can_view_other_person', 'Can view other persons')]},
        ),
    ]
