# Generated by Django 4.2.7 on 2023-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_category_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
