# Generated by Django 4.2.7 on 2023-11-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_userprofile_home_address_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_numer',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
